### ISSUE TITLE
涉及公司产品信息

### ISSUE THREAD

**Issue by ccllyy** [sooboo/MB#1]
该原型图涉及到公司产品信息，请删除该项目地址。

**Comment by sooboo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ccllyy** [comment]
> 该原型图涉及到公司产品信息，请删除该项目地址。

**Comment by sooboo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
